### ISSUE TITLE
Getting wrong values

### ISSUE THREAD

**Issue by shinhwas** [ultra1971/backtrader_ib_insync#4]
I am trying to integrate with this lib. (Thank you)
I am getting wrong value like below.
2022-02-02T19:41:54.263717,-1.000000,-1.000000,-1.000000,-1.000000,67418
2022-02-02T19:41:54.872746,0.000000,0.000000,0.000000,0.000000,0

```
    datakwargs = dict(
        timeframe=bt.TimeFrame.Seconds, compression=10,
        fromdate=dt_now,
    )

    # data0 = ibdata(dataname='EUR.USD-CASH-IDEALPRO', **datakwargs)
    data0 = ibdata(dataname='MNQ-FUT-GLOBEX-USD-202203-2', **datakwargs)
    cerebro.adddata(data0)
```

is there anything need to set or fix?

**Comment by ultra1971** [comment]
Hi,

It appears that this issue is related to IB data, pls check with another symbol to verify.

Also I suggest for this timeframe check the rtbar parameter to setup ibdata function:
      - ``rtbar`` (default: ``False``)
        If ``True`` the ``5 Seconds Realtime bars`` provided by Interactive
        Brokers will be used as the smalles tick. According to the
        documentation they correspond to real-time values (once collated and
        curated by IB)
        If ``False`` then the ``RTVolume`` prices will be used, which are based
        on receiving ticks. In the case of ``CASH`` assets (like for example
        EUR.JPY) ``RTVolume`` will always be used and from it the ``bid`` price
        (industry de-facto standard with IB according to the literature
        scattered over the Internet)
        Even if set to ``True``, if the data is resampled/kept to a
        timeframe/compression below Seconds/5, no real time bars will be used,
        because IB doesn't serve them below that level

**Comment by ultra1971** [comment]
Closed
