### ISSUE TITLE
Question on rtbar.open_

### ISSUE THREAD

**Issue by silsesquioxane** [ultra1971/backtrader_ib_insync#5]
Greatly appreciate the efforts in building the ib_insync capability into backtrader. Have a small question on the following line of code under ibdata.py line 673:

```python
AttributeError:`
            self.lines.open[0] = rtbar.open_
```

I do not recall bar having the property .open_. Is there a reason why you have inserted this exception?

**Comment by ultra1971** [comment]
Forget about it, bad documenting practice from my side. I spent some time reviewing why but I dont find a reason.
May be a IBKR contract with this attribute ?
 
Thanks to take your time in asking this in particular.

**Comment by silsesquioxane** [comment]
Thank you so much for the reply! I'm confident your code has already helped many of us 👍🏻
